const data = {
  event_type:'boda',
  nombre_novia:'Norma',
  nombre_novio:'Gerardo',
  nombre_papa_novia:'Santos Hernandez Sanchez',
  nombre_mama_novia:'Julia Cruz Salgado',
  nombre_papa_novio:'Gerardo Morales Vergara',
  nombre_mama_novio:'Eva Luna Zavaleta',
  nombre_padrino:'Miguel Taboada Hernandez',
  nombre_madrina:'Concepcion Diaz Rojas',
  frase:'Amor no es mirarse el uno al otro; es mirar juntos en la misma dirección',
  img_header:'back.webp',
  img_fondo1:'',
  img_fondo2:'',
  fecha_dia:'30',
  fecha_mes:'Noviembre',
  fecha_year:'2024',
  religiosa_hora:'12',
  religiosa_minutos:'00',
  religiosa_lugar:'Iglesia Purisima Concepción',
  religiosa_direccion:'Av. Valerio Trujano',
  religiosa_direccion_col:'Centro',
  religiosa_direccion_cd:'Tepecoacuilco de Trujano',
  religiosa_ubicacion:'https://maps.app.goo.gl/EHwdHbQQAoLL7sNEA',
  recepcion_hora:'15',
  recepcion_minutos:'00',
  recepcion_lugar:'Jardín tres virginias',
  recepcion_direccion:'Boulevard H. Colegio Militar s/n',
  recepcion_direccion_col:'Las Americas ll',
  recepcion_direccion_cd:'Iguala de la Independencia.',
  recepcion_ubicacion:'https://maps.app.goo.gl/YL2esLYdFGRA6qDC7',
  confirmacion_novia:'7331092828',
  confirmacion_novio:'7333375226',
  regalos_frase:'',
  regalos_url:'https://mesaderegalos.liverpool.com.mx/milistaderegalos/51513332'
}

export default data